services:
    _defaults:
        autowire: true
        autoconfigure: true

    Kazetenn\:
        resource: '../'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Tests/'
